Oracle case insensitive search
awslabs/aws-athena-query-federation pull request #2487
Opened 2024-12-20 20:27 UTC by aimethed

*Description of changes:*
Oracle by default upper cases everything. Glue does not support anything aside from lowercase. Originally, we were casing everything to upper case to match oracle. Now to support glue connections, we need to not do this. So we have three casing modes now, upper (default for legacy connectors), lower (default for connectors using glue connections), and now search, which will perform a case insensitive search.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-01-06 16:21 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    static final String TABLE_NAME_QUERY_TEMPLATE = "select distinct TABLE_NAME as \"TABLE_NAME\" from all_tables where OWNER = ? and lower(TABLE_NAME) = ?";
nit: can we keep the queries the same; if using capitals for the first query let's do that for the second; easier to read.

2025-01-06 16:22 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    static final String TABLE_NAME_QUERY_TEMPLATE = "select distinct TABLE_NAME as \"TABLE_NAME\" from all_tables where OWNER = ? and lower(TABLE_NAME) = ?";
I'd rather see all SQL in all caps.

2025-01-06 16:26 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    public static TableName getAdjustedTableObjectName(final Connection connection, TableName tableName, Map<String, String> configOptions)
are we assuming that if the table/schema is upper case then the columns are also upper case? and vice versa? 

If so we need to make sure we update our documentation to make this clear for the Cxs.

2025-01-06 16:27 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    public static TableName getAdjustedTableObjectName(final Connection connection, TableName tableName, Map<String, String> configOptions)
so just to add; if we think Cx wants to use Upper case it means that; Schema, Table name, and Columns area ALL upper case;

2025-01-06 16:28 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    public static TableName getAdjustedTableObjectName(final Connection connection, TableName tableName, Map<String, String> configOptions)
Right now we are only handling table/schema for case insensitivity. The documentation should reflect this.

2025-01-06 16:29 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                LOGGER.info("casing mode is `LOWER`: not adjust casing from input for TableName object. TableName:{}", tableName);
I don't think we should return this as is; we need to make sure that we lower case this; we shouldn't trust the caller to pass the original table name in lower case. it should be the responsibility of this method to do so.

2025-01-06 16:30 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            case LOWER:
same here; we shouldn't trust the caller to send the schema name lower cased; it's the responsibility of this method to ensure it.

2025-01-06 16:32 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withParameters(Arrays.asList(schemaNameInput.toLowerCase())).build();
why are we lower casing the schema name here? also nit; shouldn't it be just called `schemaName` instead of `schemaNameInput`?

2025-01-06 16:33 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                LOGGER.info("casing mode is `LOWER`: not adjust casing from input for TableName object. TableName:{}", tableName);
The decision here was that the three options would be to upper case everything, search, or take whatever the engine gives us and use that. Moving to the third option being to lowercase everything would not be an issue, it is just not the decision we made previously (I know the name LOWER is misleading, I just used it to be consistent with other connectors)

2025-01-06 16:36 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withParameters(Arrays.asList(schemaNameInput.toLowerCase())).build();
This is because the query where this is parameter is being used is:
```
"SELECT DISTINCT OWNER as \"OWNER\" FROM all_tables WHERE lower(OWNER) = ?"
```
We lowercase both sides to make it case insensitive

2025-01-06 16:37 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withParameters(Arrays.asList(schemaNameInput.toLowerCase())).build();
Agree with nit though

2025-01-06 16:37 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withQuery(SCHEMA_NAME_QUERY_TEMPLATE)
this will cause an issue; if the user that is calling this query does not have admin access they won't be able to call `all_tables` as it belongs to the Admin and Admin schema; we need to test this again and make sure our assumptions are correct; if the only way to do that; then we need to revisit this; 

Documentation points says it points to the current user's tables but lets double check. Link to docs: https://docs.oracle.com/cd/B13789_01/server.101/b10755/statviews_1190.htm#sthref1478

more over I believe the schema for `all_tables` should be all caps

2025-01-06 16:37 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withParameters(Arrays.asList((schemaName), tableNameInput.toLowerCase())).build();
same question as above.

2025-01-06 16:39 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        if (i != 1) {
shouldn't this be caught on line 114 instead? why are we waiting to finish the loop then throw the exception?

2025-01-06 16:40 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            return isGlueConnection ? OracleCasingMode.LOWER : OracleCasingMode.UPPER;
why are we always using lower casing mode for glue connection?

2025-01-06 16:41 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            return isGlueConnection ? OracleCasingMode.LOWER : OracleCasingMode.UPPER;
adding to this; Oracle by default uses upper casing no? shouldn't we default to that instead?

2025-01-06 16:42 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withQuery(SCHEMA_NAME_QUERY_TEMPLATE)
I believe this table has the behavior we want. I tested it only with the admin user (agree testing with another would be good) and it worked as intended. I believe the behavior of a user only being able to see tables/schemas they have permission for is also the behavior we want. A user shouldn't be able to query for tables they don't have permissions for.

2025-01-06 16:43 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        catch (Exception ex) {
we are catching a much wider exception here; the run time exceptions should be propagated back to the engine; in the above scenario; on line 170; if we don't have a proper casing mode set by the Cx we should check there and send an appropriate error instead of trying to catch a wider exception here.

2025-01-06 16:44 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            return isGlueConnection ? OracleCasingMode.LOWER : OracleCasingMode.UPPER;
Glue lower cases everything.

2025-01-06 16:47 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        catch (Exception ex) {
What do you mean by we should check there?
As for catching the error, we could change it to catch only the exception thrown by using `valueOf` on a value that doesn't exist in the enum. But I don't think there are any other possible errors thrown here anyway so it shouldn't change the overall result.

2025-01-06 16:47 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                LOGGER.info("casing mode is `LOWER`: not adjust casing from input for TableName object. TableName:{}", tableName);
>(I know the name LOWER is misleading, I just used it to be consistent with other connectors)

let's fix this, which other connector has lower but not lowering it. we should make it consistent

2025-01-06 16:54 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            return isGlueConnection ? OracleCasingMode.LOWER : OracleCasingMode.UPPER;
>Glue lower cases everything.

+1, We should update documentation. Stating that for connector with Glue connection. EVERYTHING IS lower cased unless you specify otherwise.

2025-01-06 16:57 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                LOGGER.info("casing mode is `LOWER`: not adjust casing from input for TableName object. TableName:{}", tableName);
Sorry I misremembered, this is set to LOWER because we did a release with this as LOWER before implementing this new Case Resolver class. So for backwards compatibility, I kept it as LOWER. If we want it to be something else (ex: DEFAULT or ENGINE) we should still support any customers who may have it set to LOWER currently by supporting LOWER

2025-01-06 17:38 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        catch (Exception ex) {
I updated this to catch the IllegalArgumentException instead of the generic Exception

2025-01-06 17:39 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                .withParameters(Arrays.asList(schemaNameInput.toLowerCase())).build();
nit addressed

2025-01-06 17:39 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            case LOWER:
we now lower case it

2025-01-06 17:39 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +                LOGGER.info("casing mode is `LOWER`: not adjust casing from input for TableName object. TableName:{}", tableName);
Changed to lower case it

2025-01-06 21:10 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +    public static TableName getAdjustedTableObjectName(final Connection connection, TableName tableName, Map<String, String> configOptions)
ack

2025-01-07 16:06 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
>      static final String LIST_PAGINATED_TABLES_QUERY = "SELECT TABLE_NAME as \"TABLE_NAME\", OWNER as \"TABLE_SCHEM\" FROM all_tables WHERE owner = ? ORDER BY TABLE_NAME OFFSET ? ROWS FETCH NEXT ? ROW
owner = ? should have case intensively match as well?

2025-01-07 16:09 UTC, chngpe requested changes
getPaginatedTables and listPaginatedTables also needs to support insensitive search. Can we making sure we are passing correct parameters?

2025-01-07 16:52 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java
>      static final String LIST_PAGINATED_TABLES_QUERY = "SELECT TABLE_NAME as \"TABLE_NAME\", OWNER as \"TABLE_SCHEM\" FROM all_tables WHERE owner = ? ORDER BY TABLE_NAME OFFSET ? ROWS FETCH NEXT ? ROW
Before we assumed that the case insensitive search from a previous call would pass through because that is the behavior of the trino engine. But other engines in the future may not do this so we should case insensitive search the schema name before passing here. This was just done.

2025-01-08 15:36 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        LOWER,      // casing mode to use whatever the engine returns (in trino's case, lower)
Update Lower comment, as we are adjusting it to lower

2025-01-08 15:38 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            throw new RuntimeException(e);
Can do you an error message, getSchemaNameCaseInsensitively for `schemaName`

2025-01-08 15:39 UTC, chngpe commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +            throw new RuntimeException(e);
nit: better message please

2025-01-08 15:41 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        if (i != 1) {
I'm not exactly following; we are checking `i=1` meaning we are expecting only 1 and only 1 result from the `resultSet`; if we get more that means the search is not conclusive since we have more than one table/schema that match the same string. So I am not sure why we can't throw the error in the loop instead of going over the entire loop.

2025-01-08 15:48 UTC, AbdulR3hman commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        if (i != 1) {
discussed offline; please ignore

2025-01-08 15:50 UTC, aimethed commented on athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleCaseResolver.java
> +        if (i != 1) {
Oh I see, I thought you were talking about the Runtime Exception thrown when catching the SQLException (the github preview was not clear). If we move the thrown error into the while loop, then we will still need to check for `i=0` outside of the loop. We also lose the information on how many matches there were (knowing 0 matches vs 2+ is helpful)

2025-01-08 16:01 UTC, AbdulR3hman approved these changes
pending other comments from Peter addressed

2025-01-08 16:32 UTC, chngpe approved these changes

2025-01-08 16:35 UTC, merged