2021.27.1 release
awslabs/aws-athena-query-federation pull request #453
Opened 2021-07-01 18:39 UTC by jobrandw

Updates the pom and yaml files for the 2021.21.1 release

I updated the `httpclient` dependency because of the security vulnerability found [here](https://github.com/awslabs/aws-athena-query-federation/security/dependabot). 

Github also suggest updating `io.netty:netty-all` to `4.1.42`, which is what we're currently [using](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-neptune/pom.xml#L103).  I checked [maven](https://mvnrepository.com/artifact/io.netty/netty-all) and all versions are suffixed with `.Final`.  I'm going to dismiss the security alert after this merges, since there is no issue.  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-01 19:28 UTC, jobrandw commented on pom.xml
> +    <version>1.2</version>
I tried making this a property, so we could just reference it in the connectors but got the error `Properties in parent definition are prohibited`.

2021-07-01 19:59 UTC, janmran submitted a review, later dismissed

2021-07-01 21:13 UTC, burhan94 commented
Lets change the version from 1.2 to 1.1.1

2021-07-01 21:13 UTC, burhan94 requested changes

2021-07-01 21:13 UTC, burhan94 commented on athena-aws-cmdb/pom.xml
> +        <version>1.2</version>
lets do 1.1.1 instead.

2021-07-01 22:22 UTC, janmran approved these changes

2021-07-02 19:04 UTC, burhan94 approved these changes

2021-07-02 19:15 UTC, merged